// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/zbx_exports.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObserverService_Initialize_FullMethodName  = "/proto.ObserverService/Initialize"
	ObserverService_SaveHistory_FullMethodName = "/proto.ObserverService/SaveHistory"
	ObserverService_SaveTrends_FullMethodName  = "/proto.ObserverService/SaveTrends"
	ObserverService_SaveEvents_FullMethodName  = "/proto.ObserverService/SaveEvents"
	ObserverService_Cleanup_FullMethodName     = "/proto.ObserverService/Cleanup"
)

// ObserverServiceClient is the client API for ObserverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObserverService defines the gRPC service interface for observer plugins.
type ObserverServiceClient interface {
	// Initialize configures the observer with connection and filter settings.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// SaveHistory processes history data.
	SaveHistory(ctx context.Context, in *SaveHistoryRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	// SaveTrends processes trend data.
	SaveTrends(ctx context.Context, in *SaveTrendsRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	// SaveEvents processes event data.
	SaveEvents(ctx context.Context, in *SaveEventsRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	// Cleanup performs cleanup of observer resources.
	Cleanup(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error)
}

type observerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObserverServiceClient(cc grpc.ClientConnInterface) ObserverServiceClient {
	return &observerServiceClient{cc}
}

func (c *observerServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, ObserverService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observerServiceClient) SaveHistory(ctx context.Context, in *SaveHistoryRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, ObserverService_SaveHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observerServiceClient) SaveTrends(ctx context.Context, in *SaveTrendsRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, ObserverService_SaveTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observerServiceClient) SaveEvents(ctx context.Context, in *SaveEventsRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, ObserverService_SaveEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observerServiceClient) Cleanup(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupResponse)
	err := c.cc.Invoke(ctx, ObserverService_Cleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObserverServiceServer is the server API for ObserverService service.
// All implementations must embed UnimplementedObserverServiceServer
// for forward compatibility.
//
// ObserverService defines the gRPC service interface for observer plugins.
type ObserverServiceServer interface {
	// Initialize configures the observer with connection and filter settings.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// SaveHistory processes history data.
	SaveHistory(context.Context, *SaveHistoryRequest) (*SaveResponse, error)
	// SaveTrends processes trend data.
	SaveTrends(context.Context, *SaveTrendsRequest) (*SaveResponse, error)
	// SaveEvents processes event data.
	SaveEvents(context.Context, *SaveEventsRequest) (*SaveResponse, error)
	// Cleanup performs cleanup of observer resources.
	Cleanup(context.Context, *CleanupRequest) (*CleanupResponse, error)
	mustEmbedUnimplementedObserverServiceServer()
}

// UnimplementedObserverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObserverServiceServer struct{}

func (UnimplementedObserverServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedObserverServiceServer) SaveHistory(context.Context, *SaveHistoryRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveHistory not implemented")
}
func (UnimplementedObserverServiceServer) SaveTrends(context.Context, *SaveTrendsRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTrends not implemented")
}
func (UnimplementedObserverServiceServer) SaveEvents(context.Context, *SaveEventsRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveEvents not implemented")
}
func (UnimplementedObserverServiceServer) Cleanup(context.Context, *CleanupRequest) (*CleanupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cleanup not implemented")
}
func (UnimplementedObserverServiceServer) mustEmbedUnimplementedObserverServiceServer() {}
func (UnimplementedObserverServiceServer) testEmbeddedByValue()                         {}

// UnsafeObserverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObserverServiceServer will
// result in compilation errors.
type UnsafeObserverServiceServer interface {
	mustEmbedUnimplementedObserverServiceServer()
}

func RegisterObserverServiceServer(s grpc.ServiceRegistrar, srv ObserverServiceServer) {
	// If the following call pancis, it indicates UnimplementedObserverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObserverService_ServiceDesc, srv)
}

func _ObserverService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserverService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserverService_SaveHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServiceServer).SaveHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserverService_SaveHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServiceServer).SaveHistory(ctx, req.(*SaveHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserverService_SaveTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServiceServer).SaveTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserverService_SaveTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServiceServer).SaveTrends(ctx, req.(*SaveTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserverService_SaveEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServiceServer).SaveEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserverService_SaveEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServiceServer).SaveEvents(ctx, req.(*SaveEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserverService_Cleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserverServiceServer).Cleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserverService_Cleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserverServiceServer).Cleanup(ctx, req.(*CleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObserverService_ServiceDesc is the grpc.ServiceDesc for ObserverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObserverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ObserverService",
	HandlerType: (*ObserverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _ObserverService_Initialize_Handler,
		},
		{
			MethodName: "SaveHistory",
			Handler:    _ObserverService_SaveHistory_Handler,
		},
		{
			MethodName: "SaveTrends",
			Handler:    _ObserverService_SaveTrends_Handler,
		},
		{
			MethodName: "SaveEvents",
			Handler:    _ObserverService_SaveEvents_Handler,
		},
		{
			MethodName: "Cleanup",
			Handler:    _ObserverService_Cleanup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/zbx_exports.proto",
}
