// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: pkg/proto/zbx_exports.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValueType represents the different data types that Zabbix can collect and store.
type ValueType int32

const (
	// FLOAT represents numeric floating-point values (Zabbix value type 0).
	ValueType_FLOAT ValueType = 0
	// CHARACTER represents character/string values (Zabbix value type 1).
	ValueType_CHARACTER ValueType = 1
	// LOG represents log file entries (Zabbix value type 2).
	ValueType_LOG ValueType = 2
	// UNSIGNED represents numeric unsigned integer values (Zabbix value type 3).
	ValueType_UNSIGNED ValueType = 3
	// TEXT represents text values (Zabbix value type 4).
	ValueType_TEXT ValueType = 4
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "FLOAT",
		1: "CHARACTER",
		2: "LOG",
		3: "UNSIGNED",
		4: "TEXT",
	}
	ValueType_value = map[string]int32{
		"FLOAT":     0,
		"CHARACTER": 1,
		"LOG":       2,
		"UNSIGNED":  3,
		"TEXT":      4,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_zbx_exports_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_pkg_proto_zbx_exports_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{0}
}

// ExportType identifies the different types of Zabbix exports.
type ExportType int32

const (
	// HISTORY identifies history data exports.
	ExportType_HISTORY ExportType = 0
	// TRENDS identifies trend data exports.
	ExportType_TRENDS ExportType = 1
	// EVENTS identifies event/problem exports.
	ExportType_EVENTS ExportType = 2
)

// Enum value maps for ExportType.
var (
	ExportType_name = map[int32]string{
		0: "HISTORY",
		1: "TRENDS",
		2: "EVENTS",
	}
	ExportType_value = map[string]int32{
		"HISTORY": 0,
		"TRENDS":  1,
		"EVENTS":  2,
	}
)

func (x ExportType) Enum() *ExportType {
	p := new(ExportType)
	*p = x
	return p
}

func (x ExportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_zbx_exports_proto_enumTypes[1].Descriptor()
}

func (ExportType) Type() protoreflect.EnumType {
	return &file_pkg_proto_zbx_exports_proto_enumTypes[1]
}

func (x ExportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportType.Descriptor instead.
func (ExportType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{1}
}

// EventValue indicates the event type (problem or recovery).
type EventValue int32

const (
	// RECOVERY indicates a trigger went from PROBLEM to OK.
	EventValue_RECOVERY EventValue = 0
	// PROBLEM indicates a trigger went from OK to PROBLEM.
	EventValue_PROBLEM EventValue = 1
)

// Enum value maps for EventValue.
var (
	EventValue_name = map[int32]string{
		0: "RECOVERY",
		1: "PROBLEM",
	}
	EventValue_value = map[string]int32{
		"RECOVERY": 0,
		"PROBLEM":  1,
	}
)

func (x EventValue) Enum() *EventValue {
	p := new(EventValue)
	*p = x
	return p
}

func (x EventValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventValue) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_zbx_exports_proto_enumTypes[2].Descriptor()
}

func (EventValue) Type() protoreflect.EnumType {
	return &file_pkg_proto_zbx_exports_proto_enumTypes[2]
}

func (x EventValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventValue.Descriptor instead.
func (EventValue) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{2}
}

// Severity indicates the severity level of a problem or log entry.
type Severity int32

const (
	// NOT_CLASSIFIED represents items with no specific severity.
	Severity_NOT_CLASSIFIED Severity = 0
	// INFORMATION represents informational items.
	Severity_INFORMATION Severity = 1
	// WARNING represents warning level items.
	Severity_WARNING Severity = 2
	// AVERAGE represents average severity items.
	Severity_AVERAGE Severity = 3
	// HIGH represents high severity items.
	Severity_HIGH Severity = 4
	// DISASTER represents disaster level items.
	Severity_DISASTER Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "NOT_CLASSIFIED",
		1: "INFORMATION",
		2: "WARNING",
		3: "AVERAGE",
		4: "HIGH",
		5: "DISASTER",
	}
	Severity_value = map[string]int32{
		"NOT_CLASSIFIED": 0,
		"INFORMATION":    1,
		"WARNING":        2,
		"AVERAGE":        3,
		"HIGH":           4,
		"DISASTER":       5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_zbx_exports_proto_enumTypes[3].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_pkg_proto_zbx_exports_proto_enumTypes[3]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{3}
}

// FilterType represents the type of filter to apply.
type FilterType int32

const (
	// TAG filters based on item/event tags.
	FilterType_TAG FilterType = 0
	// GROUP filters based on host groups.
	FilterType_GROUP FilterType = 1
	// CUSTOM filters based on custom criteria (not implemented).
	FilterType_CUSTOM FilterType = 69
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0:  "TAG",
		1:  "GROUP",
		69: "CUSTOM",
	}
	FilterType_value = map[string]int32{
		"TAG":    0,
		"GROUP":  1,
		"CUSTOM": 69,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_zbx_exports_proto_enumTypes[4].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_pkg_proto_zbx_exports_proto_enumTypes[4]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{4}
}

// Host represents a Zabbix host with its technical name and display name.
type Host struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host is the technical host name used internally by Zabbix.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// name is the visible/display name of the host as shown in Zabbix frontend.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Tag represents a key-value pair tag associated with Zabbix items or problems.
// Tags are used for categorization, filtering, and metadata purposes.
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tag is the tag name/key.
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// value is the tag value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// History represents a single Zabbix history record containing a collected item value.
// History records are created when Zabbix collects data from monitored items and
// contain the actual metric values along with metadata about when and where they were collected.
type History struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host contains the technical and display names of the host that owns this item.
	// May be null in some export configurations.
	Host *Host `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// itemid is the unique identifier of the Zabbix item.
	Itemid int64 `protobuf:"varint,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	// name is the visible/display name of the item as shown in Zabbix frontend.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// clock is the Unix timestamp (seconds since epoch) when the value was collected.
	// This represents the integer part of the collection time.
	Clock int64 `protobuf:"varint,4,opt,name=clock,proto3" json:"clock,omitempty"`
	// groups contains the list of host groups that the item's host belongs to.
	Groups []string `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	// ns is the nanoseconds component to be added to clock for precise timing.
	// Together with clock, this provides nanosecond-precision timestamps.
	Ns int64 `protobuf:"varint,6,opt,name=ns,proto3" json:"ns,omitempty"`
	// value contains the actual collected item value.
	// The interpretation depends on the value_type field:
	// - For numeric types (FLOAT, UNSIGNED): use numeric_value
	// - For text types (CHARACTER, TEXT, LOG): use string_value
	//
	// Types that are valid to be assigned to Value:
	//
	//	*History_NumericValue
	//	*History_StringValue
	Value isHistory_Value `protobuf_oneof:"value"`
	// tags contains the list of tags associated with this item.
	// Tags can be used for filtering and categorization.
	Tags []*Tag `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// value_type indicates the value type using Zabbix value type constants.
	ValueType ValueType `protobuf:"varint,10,opt,name=value_type,json=valueType,proto3,enum=proto.ValueType" json:"value_type,omitempty"`
	// timestamp is the original timestamp from the log entry (log items only).
	// Set to 0 if not available.
	Timestamp int64 `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// source is the source of the log entry (log items only).
	// Empty string if not available.
	Source string `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	// severity represents the log entry severity level (log items only).
	Severity Severity `protobuf:"varint,13,opt,name=severity,proto3,enum=proto.Severity" json:"severity,omitempty"`
	// eventid is the related event ID for log entries (log items only).
	// Set to 0 if not available.
	Eventid       int64 `protobuf:"varint,14,opt,name=eventid,proto3" json:"eventid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{2}
}

func (x *History) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *History) GetItemid() int64 {
	if x != nil {
		return x.Itemid
	}
	return 0
}

func (x *History) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *History) GetClock() int64 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *History) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *History) GetNs() int64 {
	if x != nil {
		return x.Ns
	}
	return 0
}

func (x *History) GetValue() isHistory_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *History) GetNumericValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*History_NumericValue); ok {
			return x.NumericValue
		}
	}
	return 0
}

func (x *History) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*History_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *History) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *History) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_FLOAT
}

func (x *History) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *History) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *History) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_NOT_CLASSIFIED
}

func (x *History) GetEventid() int64 {
	if x != nil {
		return x.Eventid
	}
	return 0
}

type isHistory_Value interface {
	isHistory_Value()
}

type History_NumericValue struct {
	NumericValue float64 `protobuf:"fixed64,7,opt,name=numeric_value,json=numericValue,proto3,oneof"`
}

type History_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*History_NumericValue) isHistory_Value() {}

func (*History_StringValue) isHistory_Value() {}

// Trend represents aggregated hourly statistics for a Zabbix item.
// Trends are generated by Zabbix for numeric items to provide statistical summaries
// over time periods, reducing storage requirements while maintaining useful metrics.
type Trend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host contains the technical and display names of the host that owns this item.
	// May be null in some export configurations.
	Host *Host `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// itemid is the unique identifier of the Zabbix item.
	Itemid int64 `protobuf:"varint,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	// name is the visible/display name of the item as shown in Zabbix frontend.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// clock is the Unix timestamp (seconds since epoch) representing the hour
	// for which these trend statistics were calculated.
	Clock int64 `protobuf:"varint,4,opt,name=clock,proto3" json:"clock,omitempty"`
	// count is the number of individual values that were collected and
	// aggregated to calculate these trend statistics.
	Count int64 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	// groups contains the list of host groups that the item's host belongs to.
	Groups []string `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	// min is the minimum value collected during this hour.
	Min float64 `protobuf:"fixed64,7,opt,name=min,proto3" json:"min,omitempty"`
	// max is the maximum value collected during this hour.
	Max float64 `protobuf:"fixed64,8,opt,name=max,proto3" json:"max,omitempty"`
	// avg is the average value calculated from all values collected during this hour.
	Avg float64 `protobuf:"fixed64,9,opt,name=avg,proto3" json:"avg,omitempty"`
	// tags contains the list of tags associated with this item.
	// Tags can be used for filtering and categorization.
	Tags []*Tag `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	// value_type indicates the original value type of the item.
	// Note: Only numeric types (FLOAT, UNSIGNED) have trend data generated.
	ValueType     ValueType `protobuf:"varint,11,opt,name=value_type,json=valueType,proto3,enum=proto.ValueType" json:"value_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trend) Reset() {
	*x = Trend{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trend) ProtoMessage() {}

func (x *Trend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trend.ProtoReflect.Descriptor instead.
func (*Trend) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{3}
}

func (x *Trend) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Trend) GetItemid() int64 {
	if x != nil {
		return x.Itemid
	}
	return 0
}

func (x *Trend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trend) GetClock() int64 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *Trend) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Trend) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Trend) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Trend) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Trend) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *Trend) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Trend) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_FLOAT
}

// Event represents a Zabbix problem or recovery event.
// Events are generated when triggers change state, either from OK to PROBLEM (problem events)
// or from PROBLEM to OK (recovery events). They contain information about what happened,
// when it occurred, and which hosts and groups were affected.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// clock is the Unix timestamp (seconds since epoch) when the problem was
	// detected or resolved. This represents the integer part of the event time.
	Clock int64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	// ns is the nanoseconds component to be added to clock for precise timing.
	// Together with clock, this provides nanosecond-precision timestamps.
	Ns int64 `protobuf:"varint,2,opt,name=ns,proto3" json:"ns,omitempty"`
	// value indicates the event type.
	Value EventValue `protobuf:"varint,3,opt,name=value,proto3,enum=proto.EventValue" json:"value,omitempty"`
	// eventid is the unique identifier for this specific event.
	Eventid int64 `protobuf:"varint,4,opt,name=eventid,proto3" json:"eventid,omitempty"`
	// p_eventid is the ID of the related problem event (for recovery events only).
	// This links recovery events back to their corresponding problem events.
	PEventid int64 `protobuf:"varint,5,opt,name=p_eventid,json=pEventid,proto3" json:"p_eventid,omitempty"`
	// name is the descriptive name of the problem (problem events only).
	// This is typically the trigger expression or a user-defined description.
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// severity indicates the severity level of the problem (problem events only).
	Severity Severity `protobuf:"varint,7,opt,name=severity,proto3,enum=proto.Severity" json:"severity,omitempty"`
	// hosts contains the list of hosts involved in the trigger expression that
	// generated this event (problem events only).
	Hosts []*Host `protobuf:"bytes,8,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// groups contains the list of host groups for all hosts involved in this
	// event (problem events only).
	Groups []string `protobuf:"bytes,9,rep,name=groups,proto3" json:"groups,omitempty"`
	// tags contains the list of problem tags associated with this event
	// (problem events only). Tags can be used for filtering and categorization.
	Tags          []*Tag `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetClock() int64 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *Event) GetNs() int64 {
	if x != nil {
		return x.Ns
	}
	return 0
}

func (x *Event) GetValue() EventValue {
	if x != nil {
		return x.Value
	}
	return EventValue_RECOVERY
}

func (x *Event) GetEventid() int64 {
	if x != nil {
		return x.Eventid
	}
	return 0
}

func (x *Event) GetPEventid() int64 {
	if x != nil {
		return x.PEventid
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_NOT_CLASSIFIED
}

func (x *Event) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Event) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Event) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SaveHistoryRequest is used to send history data to an observer plugin.
type SaveHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// history contains the list of history records to be saved.
	History       []*History `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHistoryRequest) Reset() {
	*x = SaveHistoryRequest{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHistoryRequest) ProtoMessage() {}

func (x *SaveHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHistoryRequest.ProtoReflect.Descriptor instead.
func (*SaveHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{5}
}

func (x *SaveHistoryRequest) GetHistory() []*History {
	if x != nil {
		return x.History
	}
	return nil
}

// SaveTrendsRequest is used to send trend data to an observer plugin.
type SaveTrendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trends contains the list of trend records to be saved.
	Trends        []*Trend `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTrendsRequest) Reset() {
	*x = SaveTrendsRequest{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTrendsRequest) ProtoMessage() {}

func (x *SaveTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTrendsRequest.ProtoReflect.Descriptor instead.
func (*SaveTrendsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{6}
}

func (x *SaveTrendsRequest) GetTrends() []*Trend {
	if x != nil {
		return x.Trends
	}
	return nil
}

// SaveEventsRequest is used to send event data to an observer plugin.
type SaveEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events contains the list of event records to be saved.
	Events        []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveEventsRequest) Reset() {
	*x = SaveEventsRequest{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEventsRequest) ProtoMessage() {}

func (x *SaveEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEventsRequest.ProtoReflect.Descriptor instead.
func (*SaveEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{7}
}

func (x *SaveEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// SaveResponse is returned by observer plugins after processing data.
type SaveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the save operation completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error contains the error message if success is false.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// records_processed indicates how many records were successfully processed.
	RecordsProcessed int64 `protobuf:"varint,3,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
	// records_failed indicates how many records failed to be processed.
	RecordsFailed int64 `protobuf:"varint,4,opt,name=records_failed,json=recordsFailed,proto3" json:"records_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{8}
}

func (x *SaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SaveResponse) GetRecordsProcessed() int64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

func (x *SaveResponse) GetRecordsFailed() int64 {
	if x != nil {
		return x.RecordsFailed
	}
	return 0
}

// InitializeRequest is sent to initialize an observer plugin.
type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the target/observer.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// connection contains the connection string for the target.
	Connection string `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// options contains key-value configuration options for the plugin.
	Options map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// exports indicates which export types are enabled for this observer.
	Exports []ExportType `protobuf:"varint,4,rep,packed,name=exports,proto3,enum=proto.ExportType" json:"exports,omitempty"`
	// filter contains the filter configuration for this observer.
	Filter        *Filter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{9}
}

func (x *InitializeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializeRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *InitializeRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InitializeRequest) GetExports() []ExportType {
	if x != nil {
		return x.Exports
	}
	return nil
}

func (x *InitializeRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// PluginInfo contains metadata about the plugin.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the plugin name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// description is a brief description of the plugin.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// author is the plugin author/maintainer.
	Author        string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{10}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// InitializeResponse is returned after initializing an observer plugin.
type InitializeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether initialization completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error contains the error message if success is false.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// plugin_info contains metadata about the plugin.
	PluginInfo    *PluginInfo `protobuf:"bytes,3,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{11}
}

func (x *InitializeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InitializeResponse) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

// Filter represents a single filter configuration with accept/reject patterns.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type indicates the filter type (tag, group or custom).
	Type FilterType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.FilterType" json:"type,omitempty"`
	// accepted contains patterns that should be accepted.
	// For TAG filters: "tag_name:tag_value_pattern"
	// For GROUP filters: "group_name_pattern"
	Accepted []string `protobuf:"bytes,2,rep,name=accepted,proto3" json:"accepted,omitempty"`
	// rejected contains patterns that should be rejected.
	// For TAG filters: "tag_name:tag_value_pattern"
	// For GROUP filters: "group_name_pattern"
	Rejected      []string `protobuf:"bytes,3,rep,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{12}
}

func (x *Filter) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_TAG
}

func (x *Filter) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *Filter) GetRejected() []string {
	if x != nil {
		return x.Rejected
	}
	return nil
}

// CleanupRequest is sent to request cleanup of observer resources.
type CleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupRequest) Reset() {
	*x = CleanupRequest{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupRequest) ProtoMessage() {}

func (x *CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupRequest.ProtoReflect.Descriptor instead.
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{13}
}

// CleanupResponse is returned after cleanup completes.
type CleanupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether cleanup completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error contains the error message if success is false.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupResponse) Reset() {
	*x = CleanupResponse{}
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResponse) ProtoMessage() {}

func (x *CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zbx_exports_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResponse.ProtoReflect.Descriptor instead.
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zbx_exports_proto_rawDescGZIP(), []int{14}
}

func (x *CleanupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CleanupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_zbx_exports_proto protoreflect.FileDescriptor

const file_pkg_proto_zbx_exports_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/zbx_exports.proto\x12\x05proto\".\n" +
	"\x04Host\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb7\x03\n" +
	"\aHistory\x12\x1f\n" +
	"\x04host\x18\x01 \x01(\v2\v.proto.HostR\x04host\x12\x16\n" +
	"\x06itemid\x18\x02 \x01(\x03R\x06itemid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05clock\x18\x04 \x01(\x03R\x05clock\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\tR\x06groups\x12\x0e\n" +
	"\x02ns\x18\x06 \x01(\x03R\x02ns\x12%\n" +
	"\rnumeric_value\x18\a \x01(\x01H\x00R\fnumericValue\x12#\n" +
	"\fstring_value\x18\b \x01(\tH\x00R\vstringValue\x12\x1e\n" +
	"\x04tags\x18\t \x03(\v2\n" +
	".proto.TagR\x04tags\x12/\n" +
	"\n" +
	"value_type\x18\n" +
	" \x01(\x0e2\x10.proto.ValueTypeR\tvalueType\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\f \x01(\tR\x06source\x12+\n" +
	"\bseverity\x18\r \x01(\x0e2\x0f.proto.SeverityR\bseverity\x12\x18\n" +
	"\aeventid\x18\x0e \x01(\x03R\aeventidB\a\n" +
	"\x05value\"\x9f\x02\n" +
	"\x05Trend\x12\x1f\n" +
	"\x04host\x18\x01 \x01(\v2\v.proto.HostR\x04host\x12\x16\n" +
	"\x06itemid\x18\x02 \x01(\x03R\x06itemid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05clock\x18\x04 \x01(\x03R\x05clock\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\tR\x06groups\x12\x10\n" +
	"\x03min\x18\a \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\b \x01(\x01R\x03max\x12\x10\n" +
	"\x03avg\x18\t \x01(\x01R\x03avg\x12\x1e\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\n" +
	".proto.TagR\x04tags\x12/\n" +
	"\n" +
	"value_type\x18\v \x01(\x0e2\x10.proto.ValueTypeR\tvalueType\"\xa9\x02\n" +
	"\x05Event\x12\x14\n" +
	"\x05clock\x18\x01 \x01(\x03R\x05clock\x12\x0e\n" +
	"\x02ns\x18\x02 \x01(\x03R\x02ns\x12'\n" +
	"\x05value\x18\x03 \x01(\x0e2\x11.proto.EventValueR\x05value\x12\x18\n" +
	"\aeventid\x18\x04 \x01(\x03R\aeventid\x12\x1b\n" +
	"\tp_eventid\x18\x05 \x01(\x03R\bpEventid\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12+\n" +
	"\bseverity\x18\a \x01(\x0e2\x0f.proto.SeverityR\bseverity\x12!\n" +
	"\x05hosts\x18\b \x03(\v2\v.proto.HostR\x05hosts\x12\x16\n" +
	"\x06groups\x18\t \x03(\tR\x06groups\x12\x1e\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\n" +
	".proto.TagR\x04tags\">\n" +
	"\x12SaveHistoryRequest\x12(\n" +
	"\ahistory\x18\x01 \x03(\v2\x0e.proto.HistoryR\ahistory\"9\n" +
	"\x11SaveTrendsRequest\x12$\n" +
	"\x06trends\x18\x01 \x03(\v2\f.proto.TrendR\x06trends\"9\n" +
	"\x11SaveEventsRequest\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.proto.EventR\x06events\"\x92\x01\n" +
	"\fSaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\x11records_processed\x18\x03 \x01(\x03R\x10recordsProcessed\x12%\n" +
	"\x0erecords_failed\x18\x04 \x01(\x03R\rrecordsFailed\"\x98\x02\n" +
	"\x11InitializeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12?\n" +
	"\aoptions\x18\x03 \x03(\v2%.proto.InitializeRequest.OptionsEntryR\aoptions\x12+\n" +
	"\aexports\x18\x04 \x03(\x0e2\x11.proto.ExportTypeR\aexports\x12%\n" +
	"\x06filter\x18\x05 \x01(\v2\r.proto.FilterR\x06filter\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\"x\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x122\n" +
	"\vplugin_info\x18\x03 \x01(\v2\x11.proto.PluginInfoR\n" +
	"pluginInfo\"g\n" +
	"\x06Filter\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.proto.FilterTypeR\x04type\x12\x1a\n" +
	"\baccepted\x18\x02 \x03(\tR\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x03(\tR\brejected\"\x10\n" +
	"\x0eCleanupRequest\"A\n" +
	"\x0fCleanupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*F\n" +
	"\tValueType\x12\t\n" +
	"\x05FLOAT\x10\x00\x12\r\n" +
	"\tCHARACTER\x10\x01\x12\a\n" +
	"\x03LOG\x10\x02\x12\f\n" +
	"\bUNSIGNED\x10\x03\x12\b\n" +
	"\x04TEXT\x10\x04*1\n" +
	"\n" +
	"ExportType\x12\v\n" +
	"\aHISTORY\x10\x00\x12\n" +
	"\n" +
	"\x06TRENDS\x10\x01\x12\n" +
	"\n" +
	"\x06EVENTS\x10\x02*'\n" +
	"\n" +
	"EventValue\x12\f\n" +
	"\bRECOVERY\x10\x00\x12\v\n" +
	"\aPROBLEM\x10\x01*a\n" +
	"\bSeverity\x12\x12\n" +
	"\x0eNOT_CLASSIFIED\x10\x00\x12\x0f\n" +
	"\vINFORMATION\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\v\n" +
	"\aAVERAGE\x10\x03\x12\b\n" +
	"\x04HIGH\x10\x04\x12\f\n" +
	"\bDISASTER\x10\x05*,\n" +
	"\n" +
	"FilterType\x12\a\n" +
	"\x03TAG\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10E2\xc7\x02\n" +
	"\x0fObserverService\x12A\n" +
	"\n" +
	"Initialize\x12\x18.proto.InitializeRequest\x1a\x19.proto.InitializeResponse\x12=\n" +
	"\vSaveHistory\x12\x19.proto.SaveHistoryRequest\x1a\x13.proto.SaveResponse\x12;\n" +
	"\n" +
	"SaveTrends\x12\x18.proto.SaveTrendsRequest\x1a\x13.proto.SaveResponse\x12;\n" +
	"\n" +
	"SaveEvents\x12\x18.proto.SaveEventsRequest\x1a\x13.proto.SaveResponse\x128\n" +
	"\aCleanup\x12\x15.proto.CleanupRequest\x1a\x16.proto.CleanupResponseB\x19Z\x17szuro.net/zms/pkg/protob\x06proto3"

var (
	file_pkg_proto_zbx_exports_proto_rawDescOnce sync.Once
	file_pkg_proto_zbx_exports_proto_rawDescData []byte
)

func file_pkg_proto_zbx_exports_proto_rawDescGZIP() []byte {
	file_pkg_proto_zbx_exports_proto_rawDescOnce.Do(func() {
		file_pkg_proto_zbx_exports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_zbx_exports_proto_rawDesc), len(file_pkg_proto_zbx_exports_proto_rawDesc)))
	})
	return file_pkg_proto_zbx_exports_proto_rawDescData
}

var file_pkg_proto_zbx_exports_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pkg_proto_zbx_exports_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_proto_zbx_exports_proto_goTypes = []any{
	(ValueType)(0),             // 0: proto.ValueType
	(ExportType)(0),            // 1: proto.ExportType
	(EventValue)(0),            // 2: proto.EventValue
	(Severity)(0),              // 3: proto.Severity
	(FilterType)(0),            // 4: proto.FilterType
	(*Host)(nil),               // 5: proto.Host
	(*Tag)(nil),                // 6: proto.Tag
	(*History)(nil),            // 7: proto.History
	(*Trend)(nil),              // 8: proto.Trend
	(*Event)(nil),              // 9: proto.Event
	(*SaveHistoryRequest)(nil), // 10: proto.SaveHistoryRequest
	(*SaveTrendsRequest)(nil),  // 11: proto.SaveTrendsRequest
	(*SaveEventsRequest)(nil),  // 12: proto.SaveEventsRequest
	(*SaveResponse)(nil),       // 13: proto.SaveResponse
	(*InitializeRequest)(nil),  // 14: proto.InitializeRequest
	(*PluginInfo)(nil),         // 15: proto.PluginInfo
	(*InitializeResponse)(nil), // 16: proto.InitializeResponse
	(*Filter)(nil),             // 17: proto.Filter
	(*CleanupRequest)(nil),     // 18: proto.CleanupRequest
	(*CleanupResponse)(nil),    // 19: proto.CleanupResponse
	nil,                        // 20: proto.InitializeRequest.OptionsEntry
}
var file_pkg_proto_zbx_exports_proto_depIdxs = []int32{
	5,  // 0: proto.History.host:type_name -> proto.Host
	6,  // 1: proto.History.tags:type_name -> proto.Tag
	0,  // 2: proto.History.value_type:type_name -> proto.ValueType
	3,  // 3: proto.History.severity:type_name -> proto.Severity
	5,  // 4: proto.Trend.host:type_name -> proto.Host
	6,  // 5: proto.Trend.tags:type_name -> proto.Tag
	0,  // 6: proto.Trend.value_type:type_name -> proto.ValueType
	2,  // 7: proto.Event.value:type_name -> proto.EventValue
	3,  // 8: proto.Event.severity:type_name -> proto.Severity
	5,  // 9: proto.Event.hosts:type_name -> proto.Host
	6,  // 10: proto.Event.tags:type_name -> proto.Tag
	7,  // 11: proto.SaveHistoryRequest.history:type_name -> proto.History
	8,  // 12: proto.SaveTrendsRequest.trends:type_name -> proto.Trend
	9,  // 13: proto.SaveEventsRequest.events:type_name -> proto.Event
	20, // 14: proto.InitializeRequest.options:type_name -> proto.InitializeRequest.OptionsEntry
	1,  // 15: proto.InitializeRequest.exports:type_name -> proto.ExportType
	17, // 16: proto.InitializeRequest.filter:type_name -> proto.Filter
	15, // 17: proto.InitializeResponse.plugin_info:type_name -> proto.PluginInfo
	4,  // 18: proto.Filter.type:type_name -> proto.FilterType
	14, // 19: proto.ObserverService.Initialize:input_type -> proto.InitializeRequest
	10, // 20: proto.ObserverService.SaveHistory:input_type -> proto.SaveHistoryRequest
	11, // 21: proto.ObserverService.SaveTrends:input_type -> proto.SaveTrendsRequest
	12, // 22: proto.ObserverService.SaveEvents:input_type -> proto.SaveEventsRequest
	18, // 23: proto.ObserverService.Cleanup:input_type -> proto.CleanupRequest
	16, // 24: proto.ObserverService.Initialize:output_type -> proto.InitializeResponse
	13, // 25: proto.ObserverService.SaveHistory:output_type -> proto.SaveResponse
	13, // 26: proto.ObserverService.SaveTrends:output_type -> proto.SaveResponse
	13, // 27: proto.ObserverService.SaveEvents:output_type -> proto.SaveResponse
	19, // 28: proto.ObserverService.Cleanup:output_type -> proto.CleanupResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_proto_zbx_exports_proto_init() }
func file_pkg_proto_zbx_exports_proto_init() {
	if File_pkg_proto_zbx_exports_proto != nil {
		return
	}
	file_pkg_proto_zbx_exports_proto_msgTypes[2].OneofWrappers = []any{
		(*History_NumericValue)(nil),
		(*History_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_zbx_exports_proto_rawDesc), len(file_pkg_proto_zbx_exports_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_zbx_exports_proto_goTypes,
		DependencyIndexes: file_pkg_proto_zbx_exports_proto_depIdxs,
		EnumInfos:         file_pkg_proto_zbx_exports_proto_enumTypes,
		MessageInfos:      file_pkg_proto_zbx_exports_proto_msgTypes,
	}.Build()
	File_pkg_proto_zbx_exports_proto = out.File
	file_pkg_proto_zbx_exports_proto_goTypes = nil
	file_pkg_proto_zbx_exports_proto_depIdxs = nil
}
